### PR TITLE
Export AsyncConstructor

### LINKED ISSUE #233: AsyncConstructor needs to be exported
Typescript emits TS4023 error because it cannot find the 'shape' of the function when emitting type declarations.  Exporting AsyncConstructor solves this.

For example when I write:

    import {createInstance} from "react-async";
    export const AsyncData = createInstance<MyData>({});

Typescript wants to generate:

    export declare const AsyncData: import("react-async").AsyncConstructor<MyData>;

However this is not possible because AsyncConstructor is not exported

### PR DESCRIPTION
**Pull request by nealeu**
So that Typescript can generate type declarations

fixes #233

### CODE REVIEW

**Comment by ghengeveld** [comment]
Thanks @nealeu! Much appreciated.

**Comment by nealeu** [comment]
Thanks @ghengeveld.  How soon will this get into a release?  It's not easy to patch around and we can't use git: npm versions against react-async (or is there another nightly source?)

**Comment by ghengeveld** [comment]
For the time being you can use the CodeSandbox version pinned above.

**Comment by nealeu** [comment]
Thanks @ghengeveld.  That's a cool feature

**Comment by nealeu** [comment]
@ghengeveld any chance of a 10.0.1 release for these.  The CodeSandbox approach was okay, but that seems to have timed out.  We could do with repeatable builds

**Comment by ghengeveld** [comment]
Hey yeah sorry it kind of slipped while I was crunching for an upcoming deadline in my daily job. I'm out of office right now but I'll try to get it released before the end of the week. Does that work for you?

**Comment by ghengeveld** [comment]
Released in [v10.0.1](https://github.com/async-library/react-async/releases/tag/v10.0.1)

**Comment by nealeu** [comment]
Thanks @ghengeveld

**Pull request merged**
