### PR TITLE
Release v10

### PR DESCRIPTION
**Pull request by ghengeveld**
This is a major release due to the migration to TypeScript. While technically it shouldn't change anything, it might be a breaking change in certain situations. Theres also a bugfix for `watchFn` and a fix for legacy browsers.

- Migrate to TypeScript [@Khartir and @phryneas in #105]
- Fix stale props being passed to promiseFn when using watchFn [@salolivares in #181]
- Avoid extending built-in JS classes [@ghengeveld in #175]
- Fix generix type declaration [@Khartir in #229]

Thanks to @Avi98, @FredKSchott and @rokoroku for reviewing and helping out.

I published a pre-release here: [v10.0.0-alpha.0](https://www.npmjs.com/package/react-async/v/10.0.0-alpha.0)

### CODE REVIEW

**Comment by ghengeveld** [comment]
This is currently blocked on failing tests for DevTools. For some reason it can't find `ActionTypes`. Most likely this is just a yarn link issue or something with TypeScript. @phryneas can you take a look?

Another issue is with the react dependency resolution script. At least on my local machine it can't find `jq` even though `node-jq` is installed and I end up with an empty package.json. Perhaps we should consider moving the forwards & backwards testing to a separate CI step, so that we have a clean workspace every time.

**Comment by ghengeveld** [comment]
I fixed the `ActionTypes` problem, apparently we had to bump the version of `react-async` in the devDeps of the root package.

**Comment by phryneas** [comment]
> Another issue is with the react dependency resolution script. At least on my local machine it can't find `jq` even though `node-jq` is installed and I end up with an empty package.json. Perhaps we should consider moving the forwards & backwards testing to a separate CI step, so that we have a clean workspace every time.

That sounds like a good idea - would also bring the build time down due to parallelization.

**Comment by ghengeveld** [comment]
I think we should move the back/forward tests in GitHub Actions. The rest can stay as it is.

**Pull request merged**
